apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: sample-app
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: exporter
      protocol: TCP
      port: 9113
      targetPort: 9113
  selector:
    app: sample-app
