kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: custom-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metricName: nginx_http_requests_per_second
      targetAverageValue: 70m
